<footer class="footer-main">

			<div class="footer-right">

				<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/?lang=en" target="_blank"><i class="fa fa-twitter"></i></a>
				<a href="https://au.linkedin.com/" target="_blank"><i class="fa fa-linkedin"></i></a>
				<a href="https://plus.google.com/discover" target="_blank"><i class="fa fa-google-plus"></i></a>

			</div>

			<div class="footer-left">

				<p class="footer-links">
					<a href="index.php">Home</a>
					·
					<a href="about_us.php">About Us</a>
					·
					<a href="contact.php">Contact Us</a>
					·
					<a href="FaQ.php">FaQ</a>					
				</p>

				<p>QeenslandCarRental &copy; 2019</p>
			</div>
</footer>
